#+TITLE: Hebi

* stack
- Harry Xu
- EXPECT_EQ snippet

- time control within emacs (TODO, deadline management)
- 572 homework lab

- Helium
- What is dynamic symbolic execution?
- CCured
- DART
- CUTE
- dynamic symbolic execution for invariant inference, ICSE 08

For array, also calculate the element range

- BeOS Haiku

- remove all Chinese in wiki

- C++ template in depth
- move semantic
- perfect forwarding
- forward iterator
- template
- unordered_set bucket

** Helium

- Input Output Data format unify
- Oracle for buffer overflow really working

- Invariant selection & validation with successfully runs
- bug studies
- More concrete details for the risks

- AST generate code: not only selected



* Old Wiki Migration
There're some pages not migrated from old wiki:
=leetcode=, =leetcode/=, =633/=, =crypto/=, =compiler/=,
=design-pattern/=.
=java/=
=coffee/=
=ruby=
=python/=
=operating-system/=
=math/=
=scholar/=
=database/=
=docker/=
=platform/=
=software/=
=web/=

#+BEGIN_HTML html
<blockquote id="quote">
</blockquote>

<script>
var i = Math.round(Math.random()*100);
var quotes = [
"你一出场别人都显得不过如此",
"你必须非常努力，才能看起来毫不费力",
"我命由我不由天",
"好运对爱笑的人情有独钟",
"成功路上，非死即伤，但别妄想我举手投降",
"我的影子想要去飞翔,我的人还在地上",
"我的脚步想要去流浪,我的心却想靠航"
];
document.getElementById("quote").innerHTML = quotes[i % quotes.length];
</script>
#+END_HTML

* Open Source Ideas
** pdf-tools
- two column view
- show citation on-the-fly

* Knowledge Place
Testing systems are typically evaluated using three metrics cite:2014-ESE-Avgerinos
1. number of real bugs found
2. node coverage (stmt coverage, finite)
3. path coverage (infinite, need approximate)


* Helium
invariants format:
- var in range [0..3432]
- relation: <, <=, >, >=, =, !=
- derived: invariants for x+y, possible operators: +, -
- address relation


- library: max, abs





* Old Wiki Migration
There're some pages not migrated from old wiki:
- =leetcode/=
- =633/=
- =crypto/=
- =compiler/=
- =java/=
- =coffee/=
- =ruby=
- =python/=
- =operating-system/=
- =math/=
- =scholar/=
- =database/=
- =docker/=
- =platform/=
- =software/=
- =web/=


* Note Book

** Long Term TODO
- color theme!

** concepts to understand

** Every day
- SE papers
- AI papers
- Leetcode
- Helium

** Routine
- String split and trim algorithm
- sort algorithms

** Code to write:
- compiler


** Languages to learn:
- lua
- Scala: http://www.scala-lang.org/
- OpenGL
- CUDA
- haskell

* Links

Keep an eye on the most recent conference papers!
- [[https://issta2016.cispa.saarland/program/][ISSTA16]]

** Websites
*** Learning Websites
- [[https://www.coursera.org/][Coursera]]
- [[https://leetcode.com/][Leetcode]]

*** Reading Websites:
- Hacker News: https://news.ycombinator.com/
- Reddit Programming: https://www.reddit.com/r/programming/
- Reddit Emacs; https://www.reddit.com/r/emacs/

*** Github Repos
- [[https://github.com/papers-we-love/papers-we-love][papers-we-love/papers-we-love]]
- [[https://github.com/ivoarch/.dot-org-files][ivoarch/.dot-org-files]]

*** Other Links:
- http://en.bookfi.net/

* Advice
** About interruption
From https://jaxenter.com/aaaand-gone-true-cost-interruptions-128741.html
#+BEGIN_QUOTE
When you’re operating on the maker’s schedule, meetings are a disaster.
A single meeting can blow a whole afternoon, by breaking it into two pieces each too small to do anything hard in.
Plus you have to remember to go to the meeting. That’s no problem for someone on the manager’s schedule.
There’s always something coming on the next hour; the only question is what.
But when someone on the maker’s schedule has a meeting, they have to think about it.

I find one meeting can sometimes affect a whole day.
A meeting commonly blows at least half a day, by breaking up a morning or afternoon.
But in addition there’s sometimes a cascading effect.
If I know the afternoon is going to be broken up, I’m slightly less likely to start something ambitious in the morning.
I know this may sound oversensitive, but if you’re a maker, think of your own case.
Don’t your spirits rise at the thought of having an entire day free to work, with no appointments at all? Well, that means your spirits are correspondingly depressed when you don’t.
And ambitious projects are by definition close to the limits of your capacity. A small decrease in morale is enough to kill them off.

Working late at night might sound like a good idea because there are no (or at least less) interruptions but even programmers need to sleep if they want to avoid burnout.
#+END_QUOTE


From https://www.reddit.com/r/programming/comments/4zp5dt/the_true_cost_of_interruptions_game_developer/:

#+BEGIN_QUOTE
Developers don't try to do hard things when an interruption is impending.

Honestly it's one reason I like instant messaging, whether individual or in a group conversation (IRC, Slack, etc.).
I can see a notification out of the corner of my eye, but it doesn't have the same urgency to respond as, say, a phone call.
At a minimum it lets me complete the thought (e.g. finish writing a paragraph) before I look at the message.

It's also a reason to appreciate working remotely. Nobody "just happens to stop by my desk."
#+END_QUOTE

bibliography:/home/hebi/github/bibliography/hebi.bib

* Task Log
- 572 homework 2
