#+TITLE: Latex
* Installation
  To see what is your tex home:
  #+BEGIN_EXAMPLE
kpsewhich -var-value=TEXMFHOME
  #+END_EXAMPLE

  It should be something like "~/texmf".
  Putting class and style file into correct path inside that folder
  will enable global usage of the class.
  check whether it works or not:
  #+BEGIN_EXAMPLE
kpsewhich sig-alternate-05-2015.cls
  #+END_EXAMPLE

  Typically you don't need to update database, but if you want,
  Command to update the =ls-R= database
  - =texhash=
  - =mktexlsr=
* Literals
** Symbols

   - alpha beta :: =\alpha= (\alpha) =\beta= (\beta) =\gamma= (\gamma)
                   =\theta= (\theta) =\phi= (\phi) =\varphi= (\varphi) =\xi=
                   (\xi) =\mu= (\mu) =\pi= (\pi) =\rho= (\rho) =\sigma=
                   (\sigma) =\epsilon= (\epsilon) =\partial= (\partial)
                   =\ell= (\ell)
   - spacing :: =\quad= (\quad) =\qquad= (\qquad)
   - logic :: =\cup= (\cup) =\bigcup= (\bigcup) =\cap= (\cap) =\vee=
              (\vee) =\wedge= (\wedge) =\in= (\in) =\notin= (\notin)
              =\neg= (\neg) =\subset= (\subset) =\subseteq=
              (\subseteq) =\supset= (\supset) =\supseteq= (\supseteq)
              =\le= (\le) =\ge= (\ge) =\neq= (\neq) =\forall=
              (\forall) =\exists= (\exists)
   - arrow :: =\leftarrow= (\leftarrow) =\rightarrow= (\rightarrow)
              =\Rightarrow= (\Rightarrow) =\Leftarrow= (\Leftarrow)
              =\Leftrightarrow= (\Leftrightarrow) =\longrightarrow=
              (\longrightarrow)
   - accents :: =\hat{a}= (\hat{a}) =\vec{x}= (\vec{x})
   - math :: =\infty= (\infty) =\propto= (\propto) =\lfloor= (\lfloor)
             =\rfloor= (\rfloor) =\lceil= (\lceil) =\rceil= (\rceil)
             =\sum= (\sum) =\int= (\int) =\prod= (\prod) =\times= (\times)
             =\ldots= ( \ldots ) =\frac{a}{b}= (\frac{a}{b}) =\sqrt{n}=
             (\sqrt{n}) =\overline{abc}= (\overline{abc})
   - mark :: =\checkmark= (\checkmark)

** Font size
   It can be used after table environment
   #+BEGIN_EXAMPLE latex
\begin{table}
\small
% ..
\end{table}
   #+END_EXAMPLE

   In org mode:
   #+BEGIN_EXAMPLE
#+ATTR_LATEX: :font \small
   #+END_EXAMPLE

   The different size reference
   - tiny
   - scriptsize
   - footnotesize
   - small
   - normalsize
   - large
   - Large
   - LARGE
   - huge
   - Huge

* General Syntax
** structure
*** enumerate
    #+begin_src latex
\begin{enumerate}
  \item xxx
  \item xxx
  \item xxx
\end{enumerate}
    #+end_src

*** itemize

    #+begin_src latex
\begin{itemize}
  \item like this,
  \item and like this.
\end{itemize}
    #+end_src

*** description

    #+begin_src latex
\begin{description}
  \item[Word] Definition
  \item[Concept] Explanation
  \item[Idea] Text
\end{description}
    #+end_src

** table & figure
*** table

    #+begin_src latex
\begin{table}
\centering
\begin{tabular}{l|r}
Item & Quantity \\\hline
Widgets & 42 \\
Gadgets & 13
\end{tabular}
\caption{\label{tab:widgets}An example table.}
\end{table}
    #+end_src

*** figure

    #+begin_src latex
\begin{figure}
  \centering
  \includegraphics[width=0.3\textwidth]{frog.jpg}
  \caption{\label{fig:frog}This frog was uploaded to writeLaTeX via the project menu.}
\end{figure}
    #+end_src

    `figure*` can make the figure two column

** label & reference

   label:

   #+begin_src latex
\label{xxx}
\ref{xxx}

\label{xx:yy}
\ref{xx:yy}
   #+end_src

** in-pdf comment
   #+BEGIN_SRC latex
\todo{Here's a comment in the margin!}
\todo[inline, color=green!40]{This is an inline comment.}
   #+END_SRC



* Beamer
#+BEGIN_EXAMPLE
#+AUTHOR: Hebi Li
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+BEAMER-FRAME-LEVEL: 2
#+BEAMER_THEME: Madrid
#+OPTIONS: H:2 toc:nil num:t author:t
#+LATEX_HEADER: \lstset{numbers=none,frame=shadowbox, basicstyle=\scriptsize, breaklines=true, basewidth={0.45em,0.3em}, stringstyle=\ttfamily}
#+END_EXAMPLE

Themes
- Madrid
- CambridgeUS

* Packages
** titlesec
   http://ctan.org/pkg/titlesec
** geometry
   The the default for LaTeX is to have no indent after sectional headings.
   Thus the first paragraph will have no indent.
   To indent it, ~\usepackage{indentfirst}~.

   The default =article= class has too much margin.
   To change it:
   #+begin_src latex
%% this does not work
%% the default should be 1in, 11pt
%% \documentclass[a4paper, margin=1in, 11pt]{article} 
\usepackage{geometry}
\geometry{margin=1in}
   #+end_src

** fancyhdr
   use headers and footers
   #+begin_src latex
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhf{}
  \rhead{573 HW1}
  \lhead{Hebi Li}
  \rfoot{Page \thepage}
  %% \lfoot{xxx}
  %% \cfoot{xxx}
   #+end_src

** qtree
   The =[= and =]= should be surrounded by spaces!

   #+BEGIN_SRC latex
\usepackage{qtree}
\Tree [ .S [ .S [ .S a ] [ .S a ] + ] [ .S a ] * ]
   #+END_SRC

** listings
*** Global setting:

Frame:
#+BEGIN_SRC latex
\lstset{frame=single}
\lstset{frame=trBL} % lowercase for single frame, upper case for double
\lstset{frameround=fttt} % from upper right, clock-wise
%% frame should not be too fancy
\lstset{framextopmargin=50pt,frame=bottomline}
#+END_SRC

Style:

#+BEGIN_SRC latex
%% after using courier, the font here will be much better
\usepackage{listings}
\usepackage{courier}
\lstset{basicstyle=\footnotesize\ttfamily,breaklines=true}

%% none, left
\lstset{numbers=left, numberstyle=\tiny}
\lstset{stringstyle=\ttfamily}
\lstset{keywordstyle=\color{black}\bfseries\underbar} % the keyword
\lstset{showstringspaces=false}
\lstset{showspaces=false, showtabs=false} % the annoying space indicators
#+END_SRC


emphasize

#+BEGIN_SRC latex
\lstset{language=C}
\lstset{emph={key1,word2}, emphstyle-\underbar}
\lstset{emph={square}, emphstyle=\color{red}
        emph={[2]root,base}, emphstyle={[2]\color{blue}}}
\lstset{morecomment=[s][\color{blue}]{/*+}{*/} % /*+ xxx */ will be in blue!
        morecomment=[s][\color{red}]{/*-}{*/}}
#+END_SRC

Style arbitrary content:
#+BEGIN_SRC latex
\lstset{escapeinside={(*@}{@*)}}
\begin{lstlisting}
(*@\color{red}everything here will be red@*)
\end{lstlisting}
#+END_SRC


*** Local setting:
#+BEGIN_SRC latex
\begin{lstlisting}[float, caption=The caption] % using caption will cause the title be: "listing 1: xxx"
\end{lstlisting}
#+END_SRC

- ~title=this is title~ :: using title will remove the "listing 1:"
- ~backgroundcolor=\color{yellow}~ ::



** tikz
see [[file:tikz.org][tikz]]

** ulem
- uline :: regular underline
- uuline :: double underline
- uwave :: wave
- sout :: strike out
- xout :: dense cross out
- dashuline :: dash
- dotuline :: dot

** TODO pdfcomment
** todonotes
#+BEGIN_SRC latex
% use the package
\usepackage[textsize=footnotesize, color=green!0]{todonotes}
% HACK: set length so that the paper can have better width for margin
\setlength{\marginparwidth}{1.5cm}

\todo[fancyline]{Here's a comment in the margin}
\todo[noline]{comment}
\todo[inline]{inline comment}
#+END_SRC


* Bibliography
cite link (need to load a package like =hyperref= or =url=)

#+BEGIN_EXAMPLE
@misc{WinNT,
  title = {{MS Windows NT} Kernel Description},
  howpublished = {\url{http://web.archive.org/web/20080207010024/http://www.808multimedia.com/winnt/kernel.htm}},
  note = {Accessed: 2010-09-30}
}
#+END_EXAMPLE
