#+TITLE: Linux

* App
- File explorer: konquerer
- Image viewer: feh

* Job control
- =C-z= to suspend.
- =fg= to bring it to foreground.
- =jobs= to list all background jobs,
  and =kill %1= to kill the first.

* Install fonts
- OTF: OpenType
- TTF: TrueType
- EOT: Embedded Open Type
- WOFF: Web Open Font Format

To install:

#+BEGIN_EXAMPLE
cp *.otf ~/.fonts
sudo fc-cache
fc-list
#+END_EXAMPLE



* Power management
No extra software needed! =systmed= can handle it, by =acpid=.
The configure file is =/etc/systemd/logind.conf=.
=man logind.conf= for details.

#+BEGIN_EXAMPLE
HandlePowerKey=hibernate
HandleLidSwitch=suspend
#+END_EXAMPLE

hibernate will save to disk, while suspend save to ram.
Both of them will resume to the current status.

* Grub
** Introduction
Use grub 2 instead of grub legacy. For a quick look at what they look like:

Grub Legacy =boot/grub/menu.lst=:
#+BEGIN_EXAMPLE
title           Debian GNU/Linux
root            (hd0,2)
kernel          /vmlinuz root=/dev/hda3 ro
initrd          /initrd.img
#+END_EXAMPLE

Grub 2 =/boot/grub/grub.cfg=:
#+BEGIN_EXAMPLE
menuentry "Debian GNU/Linux" {
        set root=(hd0,3)
        linux /vmlinuz root=/dev/hda3
        initrd /initrd.img
}
#+END_EXAMPLE

Note that the root is =(hd0,2)= in grub legacy vs. =(hd0,3)= in grub 2.

** Grub 2
The menu configure file is located at =/boot/grub/grub.cfg=.
It is generated by =/usr/sbin/update-grub= (8) using templates from =/etc/grub.d/*= and settings from =/etc/default/grub=.

* Run level
Use debian as example distribution.

The default run level is 2, corresponding to =/etc/rc2.d/XXX= scripts.
By default there's no difference between level 2 to 5.

** Run level description
- 0: halt
- S: single user mode on boot
- 1: single user mode, switched from multi-user mode
- 2: multi-user mode
- 3,4,5
- 6: reboot

- =telinit(8)= can change the run level dynamically.
- =runlevel(8)= check current run level

Those scripts starts with "S" or "K" meaning =start= or =stop= sent to =systemd= utility.
Those scripts are symbol linked to =../init.d/xxx=.
