#+TITLE: Linux


One of the most wired error I had (multiple times) is that,
my dist is full.
Then I cannot log into my account. Hopefully the home partition is
separate from root partition, I can still log into root to discover
this thing.

One of the situation I encountered is the =xsession-errors= file is more than 400G.

- Debian Wiki: https://wiki.debian.org/
- FreeBSD: https://www.freebsd.org/

* System
  - =iostat= :: to monitor the IO usage. (from =sysstat= package)
  * =id= :: show the group information of current user
  * =dmesg= :: kernel log

* Shell Interaction
  * ~Ctrl-s~ :: stop the screen
  * ~Ctrl-q~ :: recover the screen
  * ~Shift-pageup/down~ :: page up & down
  * ~shift-Insert~ :: paste
  * ~Ctrl-l~ :: clear
* App
  - File explorer: konquerer
  - Image viewer: feh

  - image processing: graphicsmagick, imagemagick

** Speech recognition engines
   - =gnustep-gui-runtime= :: =say "hello"= It is not working yet
   - =festival= :: =echo "hello" | festival --tts= The speech is pretty smooth
   - =speech-dispatcher= :: =spd-say "hello"= quality is not that good
   - =espeak= :: =espeak "hello"= quality is not that good

* Prompt
  * prompt($PS1-4)
    * ~\d~: date
    * ~\D{format}~
    * ~\h~: hostname
    * ~\H~: full hostname
    * ~\t~: time 24hour HH::MM::SS
    * ~\T~: time 12hour HH::MM::SS
    * ~\@~: time 12hour am/pm
    * ~\A~: time 24hour HH::MM
    * ~\w~: current working directory
    * ~\W~: basename of $PWD
** escape color
   * 1: bold
   * 4: underline
   * 30-37: black, red, green, yellow, blue, pink, cyan, white
   * 40-47: background
   * 90-97: light
   * 100-107: light background

   example:
   * ~\033[1;4;32;45m~
   * ~\e[32;45m~
   * ~\e[0m~

   in PS1, use:
   * ~\[\033[32;45m\]~



* Job control
  - =C-z= to suspend.
    - =top=, then you can see the CPU usage and all process IDs. Simply press =k= and enter the PID can kill the process.
  * refer a job
    - ~%n~: job number
    - ~%%~: current job
    - ~%+~: current job
    - ~%-~: previous job
    - ~%~: current job
    - ~%ce~: the job "ce"
    - ~%?ce~: the job, whose command has "ce"
  - =jobs= :: list all background jobs
  * =fg %1= :: continue it in foreground
  * =bg %1= :: continue it in background
  * =kill %1= :: kill the job (first)

* Install fonts
  - OTF: OpenType
  - TTF: TrueType
  - EOT: Embedded Open Type
  - WOFF: Web Open Font Format

  To install:

  #+BEGIN_EXAMPLE
cp *.otf ~/.fonts
sudo fc-cache
fc-list
  #+END_EXAMPLE



* Power management
  No extra software needed! =systmed= can handle it, by =acpid=.
  The configure file is =/etc/systemd/logind.conf=.
  =man logind.conf= for details.

  #+BEGIN_EXAMPLE
HandlePowerKey=hibernate
HandleLidSwitch=suspend
  #+END_EXAMPLE

  hibernate will save to disk, while suspend save to ram.
  Both of them will resume to the current status.

* Grub
** Introduction
   Use grub 2 instead of grub legacy. For a quick look at what they look like:

   Grub Legacy =boot/grub/menu.lst=:
   #+BEGIN_EXAMPLE
title           Debian GNU/Linux
root            (hd0,2)
kernel          /vmlinuz root=/dev/hda3 ro
initrd          /initrd.img
   #+END_EXAMPLE

   Grub 2 =/boot/grub/grub.cfg=:
   #+BEGIN_EXAMPLE
menuentry "Debian GNU/Linux" {
        set root=(hd0,3)
        linux /vmlinuz root=/dev/hda3
        initrd /initrd.img
}
   #+END_EXAMPLE

   Note that the root is =(hd0,2)= in grub legacy vs. =(hd0,3)= in grub 2.

** Grub 2
   The menu configure file is located at =/boot/grub/grub.cfg=.
   It is generated by =/usr/sbin/update-grub= (8) using templates from =/etc/grub.d/*= and settings from =/etc/default/grub=.

* Run level
  Use debian as example distribution.

  The default run level is 2, corresponding to =/etc/rc2.d/XXX= scripts.
  By default there's no difference between level 2 to 5.

** Run level description
   - 0: halt
   - S: single user mode on boot
   - 1: single user mode, switched from multi-user mode
   - 2: multi-user mode
   - 3,4,5
   - 6: reboot

   - =telinit(8)= can change the run level dynamically.
   - =runlevel(8)= check current run level

   Those scripts starts with "S" or "K" meaning =start= or =stop= sent to =systemd= utility.
   Those scripts are symbol linked to =../init.d/xxx=.


* LD_LIBRARY_PATH
  On =CentOS=, the default =LD_LIBRARY_PATH= does not contains the =/usr/local/lib=.
  The consequence is the =-lpugi= and =-lctags= are not recognized because they are put in that directory.
  Set it, or edit =/etc/ld.conf.d/local.conf= and add the path.
  After that, run =ldconf -v= as root to update the database.

  Also, the error:
  #+BEGIN_QUOTE
  Linux error while loading shared libraries: cannot open shared object file: No such file or directory
  #+END_QUOTE

  is also because the cache is not updated.
  So the solution is =sudo ldconfig=


* Networking using NetworkManager
  Install network-manager package, and:

  Start the service
  #+BEGIN_EXAMPLE
systemctl enable NetworkManager
  #+END_EXAMPLE
  change =/etc/NetworkManager$/NetworkManager.conf= to:

  #+BEGIN_EXAMPLE
[ifupdown]
managed=true
  #+END_EXAMPLE

  restart
  #+BEGIN_EXAMPLE
systemctl restart NetworkManager
  #+END_EXAMPLE


** add a wifi connection
   #+BEGIN_EXAMPLE
nmcli device wifi list
nmcli device wifi connect IASTATE
nmcli device wifi connect ID password pwd
   #+END_EXAMPLE

* Remove viewer

The lab machines are accessed via spice. The client for spice is
virt-viewer. It can be installed through package manager. The actual
client is called remote-viewer, which is shipped with virt-viewer. So
the command to connect to the .vv file: =remove-viewer console.vv=.
