#+TITLE: Model Checking

The book: cite:2004-Book-Huth-Logic

* Kripke Structure (KS)
** syntax
1. S: set of states
2. T: transitions: \subsetof SxS
   - /left total/: forall s, exists s', s,s' \in T. I.e. every state
     has an outgoing edge.
3. L: labeling function, e.g. busy, non-busy. S->P(AP): P: powerset,
   AP: set of propositions

- Computation model :: pick a state, and unfold (infinite because of
     left total) all transitions. It is a tree. Thus it is also called
     /computation tree model/.
- Path :: ordered sequence of states in the computation model (also
          infinite)
- Computation Tree Temporal Logic (CTL)

phi is the /formula/, i.e. the aV(b^c) thing, in propositional logic.

#+begin_example
\phi :: true | false |
        AP (atom proposition) |
        \not \phi | \phi \vee \phi | \phi \hedge \phi
        AX phi
        EX phi
        AF phi
        EF
        AG
        EG
        A (phi U phi)
        E (phi U phi)
#+end_example

- E: Exists a path
- A: along All path
- X: in the neXt state
- F: Finally in a state
- G: Globally in all states
- U: until
** semantic
It means, states of KS where the given CTL formula is satisfied.

Given KS M and some state s in M
- $M,s \models true$: always true
- $M,s \not\models false$
- M,s \models p iff p \in L(s) where L is the label function
- M,s \not\models \phi iff \phi \not\in L(s) ??
- M,s \models AX \phi iff \forall \pi \in Path(s) \pi[1] \models
  \phi, where Path(s) is all possible paths start from s, and \pi[i]
  means the i-th item on the path.

In temporal logic, future starts from right now. So
- $M,s \models AF \phi$, iff $\forall \pi \in Path(s), \exists i \ge 0,
  \pi[i] \models \phi$. Pay attention to the $i \ge 0$.
- $M,s \models AG \phi$, iff $\forall \pi \in Path(s), \forall i \ge 0, \pi[i] \models \phi$

- M,s \models A(\phi_1 \union \phi_2) iff there is a state that phi_2
  satisfy, the before it on the path, phi_1 always holds.
  - iff $\forall \pi \in Path(s), \exists i \ge 0, \pi[i] \models
    \phi_2 \wedge \forall j < i, \pi[j] \models \phi_1$
