#+TITLE: A tmp

* Similarity metrics
** Token based
*** Jaccard coefficient/index
/Jaccard index/, also known as the /Jaccard similarity coefficient/, compares two sets, A and B.

$J(A,B) = \frac{A \cap B}{A \cup B}$

*** Cosine similarity
- most widely used
- typically the terms are weighted with TF-IDF

**** TF-IDF
- In information retrieval.
- short for /term frequency–inverse document frequency/
- a numerical statistic that is intended to reflect how important a word is to a document

- /term frequency/:: the number of times a term occurs in a document. E.g. "good" appears 3 times.
- /inverse document frequency/:: this is to fix the word "the" appears so often and not that useful.
  $idf(t,D) = log \frac{N}{|\{d \in D : t \in d\}}$
  Meaning the total number of documents, divided by the documents that contains the word =t=.
- /term frequency–inverse document frequency/:: tfidf(t, d) = tf(t, d) * idf(t, D)
Example:

| term    | doc 1 | doc 2 |
|---------+-------+-------|
| this    |     1 |     1 |
| is      |     1 |     1 |
| a       |     2 |       |
| sample  |     1 |       |
| another |       |     2 |
| example |       |     3 |

- tf("this", d1) = 1/5
- tf("this", d2) = 1/7
- idf("this", D) = log(2/2) = 0
- tfidf("this", d1) = 1/5 * 0 = 0
- tfidf("this", d2) = 1/7 * 0 = 0

Both the tfidf is 0, meaning "this" is not very informative.

- tf("example", d1) = 0 / 5
- tf("example", d2) = 3/7
- idf("example", D) = log(2/1) = 0.3
- tfidf("example", d1) = 0 / 5 * 0.3 = 0
- tfidf("example", d2) = 3 / 7 * 0.3 = 0.13

*** Levenshtein distance

** Syntax based
*** KL divergence
/Kullback–Leibler divergence/
#+BEGIN_QUOTE
KL divergence between language models (it is actually somewhere between token and syntax)
#+END_QUOTE
*** Tree kernels
https://en.wikipedia.org/wiki/Tree_kernel
*** Tree edit distance
extensions of Levenshtein into the tree setting
*** Graph kernels
defined on dependency graphs (counterpart in PA is CFG?)


* camera
- Card camera
- Single lens reflex (SLR) camera :: start from 1990
- digital single-lens reflex camera (digital SLR or DSLR) :: not mirrorless camera, start from 2000
- mirrorless camera :: start from 2010, https://en.wikipedia.org/wiki/Mirrorless_interchangeable-lens_camera
- Advanced Photo System type-C (APS-C) :: a sensor format, lens format
